package com.astrayzjt.faultpilot.common.domain;

public enum EvidenceType {
    API_LATENCY_REGRESSION,
    PROCESS_CPU_HIGH,
    PROCESS_CPU_NORMAL,
    GC_PRESSURE_NOT_FOUND,
    REPEATED_RUNNABLE_STACK,
    THREAD_POOL_ACTIVE_AT_MAX,
    THREAD_POOL_QUEUE_GROWING,
    BLOCKING_TASK_FOUND,
    THREAD_POOL_NORMAL,
    DB_POOL_PENDING_HIGH,
    DB_POOL_ACTIVE_AT_MAX,
    CONNECTION_HOLDING_QUERY_FOUND,
    SLOW_SQL_FOUND,
    ABNORMAL_EXECUTION_PLAN,
    API_AND_SQL_TIME_CORRELATED,
    DOWNSTREAM_LATENCY_HIGH,
    SLOW_CHILD_SPAN_FOUND,
    DATA_UNAVAILABLE
}

