package com.astrayzjt.faultpilot.common.domain;

public enum IncidentStatus {
    DRAFT, NEEDS_INPUT, READY_TO_START, ACCEPTED, INVESTIGATING,
    DIAGNOSED, WAITING_ACTION_CONFIRMATION, REMEDIATING, VERIFYING,
    RESOLVED, INCONCLUSIVE, FAILED, CANCELED
}

